INSERT INTO books (title, author, year, pages)
VALUES ('Программирование на языке Go!', 'Марк Саммерфильд', 2008, 239),
       ('Толковый словарь сетевых терминов и аббревиатур', 'М., Вильямс',2003, 652),
       ('Python for Data Analysis', 'Уэс Маккинни', 2018, 448),
       ('Thinking in Java (4th Edition)', 'Брюс Эккель', 2015, 232),
       ('Introduction to Algorithms', 'Томас Кормен, Чарльз Лейзерсон, Рональд Ривест, Клиффорд Штайн', 1998, 750),
       ('JavaScript Pocket Reference', 'Дэвид Флэнаган', 2018, 154),
       ('Adaptive Code via C#: Class and Interface Design, Design Patterns, and SOLID Principles', 'Гэри Маклин Холл', 2008, 448),
       ('SQL: The Complete Referenc', 'Джеймс Р. Грофф', 2018, 448),
       ('PHP and MySQL Web Development', 'Люк Веллинг', 2018, 448),
       ('Статистический анализ и визуализация данных с помощью R', 'Сергей Мастицкий', 2018, 448),
       ('Computer Coding for Kid', 'Джон Вудкок', 2018, 448),
       ('Exploring Arduino: Tools and Techniques for Engineering Wizardry', 'Джереми Блум', 2018, 448),
       ('Программирование микроконтроллеров для начинающих и не только', 'А. Белов', 2018, 448),
       ('The Internet of Things', 'Сэмюэл Грингард', 2018, 448),
       ('Sketching User Experiences: The Workbook', 'Сет Гринберг', 2018, 448),
       ('InDesign CS6', 'Александр Сераков', 2018, 448),
       ('Адаптивный дизайн. Делаем сайты для любых устройств', 'Тим Кедлек', 2018, 448),
       ('Android для разработчиков', 'Пол Дейтел, Харви Дейтел', 2018, 448),
       ('Clean Code: A Handbook of Agile Software Craftsmanship', 'Роберт Мартин', 2018, 448),
       ('Swift Pocket Reference: Programming for iOS and OS X', 'Энтони Грей', 2018, 448),
       ('NoSQL Distilled: A Brief Guide to the Emerging World of Polyglot Persistence', 'Мартин Фаулер, Прамодкумар Дж. Садаладж', 2018, 448)
       ('Head First Ruby', 'Джей Макгаврен', 2018, 448),
       ('Practical Vim', 'Дрю Нейл', 2018, 448);